[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    '@uniswap-v3/=lib/v3-core/contracts',
    '@uniswap-periphery/=lib/v3-periphery/contracts'
]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
