[profile.default]
src = "src"
out = "out"
libs = ["lib"]
--via-ir = true
remappings = [
    "openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    '@uniswap/v2-core/contracts/=lib/v2-core/contracts',
    '@uniswap/v2-periphery/contracts/=lib/v2-periphery/contracts',
    '@uniswap/v2-periphery/=lib/v2-periphery/',
    'permit2/=lib/permit2/src/',
    'sign-utils/=lib/Sign-Utils/src/',
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
